import { FeatureConfig } from '@/types/prediction';

export const featureConfig: FeatureConfig[] = [
    // Planetary Features (Core)
    {
        id: 'koi_period',
        label: 'Orbital Period',
        description: 'Time taken for the planet to orbit its star (days)',
        min: 0,
        max: 1000,
        required: true,
        category: 'core',
    },
    {
        id: 'koi_duration',
        label: 'Transit Duration',
        description: 'Duration of the planetary transit (hours)',
        min: 0,
        max: 100,
        required: true,
        category: 'core',
    },
    {
        id: 'koi_depth',
        label: 'Transit Depth',
        description: 'Fraction of stellar flux lost during transit (ppm)',
        min: 0,
        max: 1000000,
        required: true,
        category: 'core',
    },
    {
        id: 'koi_prad',
        label: 'Planetary Radius',
        description: 'Radius of the planet in Earth radii',
        min: 0,
        max: 200,
        required: true,
        category: 'core',
    },
    {
        id: 'koi_impact',
        label: 'Impact Parameter',
        description: 'Sky-projected distance between disk centers',
        min: 0,
        max: 5,
        required: true,
        category: 'advanced',
    },
    {
        id: 'koi_model_snr',
        label: 'Model SNR',
        description: 'Transit depth normalized by noise',
        min: 0,
        max: 10000,
        required: true,
        category: 'advanced',
    },
    {
        id: 'koi_num_transits',
        label: 'Number of Transits',
        description: 'Number of transit events observed',
        min: 0,
        max: 1000,
        required: true,
        category: 'advanced',
    },
    {
        id: 'koi_ror',
        label: 'Planet-Star Radius Ratio',
        description: 'Ratio of planet radius to stellar radius',
        min: 0,
        max: 1,
        required: true,
        category: 'advanced',
    },

    // Stellar Features (Core)
    {
        id: 'st_teff',
        label: 'Stellar Temperature',
        description: 'Effective temperature of the star (Kelvin)',
        min: 0,
        max: 10000,
        required: true,
        category: 'core',
    },
    {
        id: 'st_mass',
        label: 'Stellar Mass',
        description: 'Mass of the star in solar masses',
        min: 0,
        max: 20,
        required: true,
        category: 'core',
    },
    {
        id: 'st_radius',
        label: 'Stellar Radius',
        description: 'Radius of the star in solar radii',
        min: 0,
        max: 200,
        required: true,
        category: 'core',
    },

    // Stellar Features (Advanced)
    {
        id: 'st_logg',
        label: 'Stellar Surface Gravity',
        description: 'Base-10 logarithm of surface gravity (cm/s^2)',
        min: 0,
        max: 6,
        required: true,
        category: 'advanced',
    },
    {
        id: 'st_met',
        label: 'Stellar Metallicity',
        description: 'Logarithm of iron-to-hydrogen ratio',
        min: -2,
        max: 1,
        required: true,
        category: 'advanced',
    },
    {
        id: 'st_dens',
        label: 'Stellar Density',
        description: 'Density of the star (g/cm^3)',
        min: 0,
        max: 100,
        required: true,
        category: 'advanced',
    },

    // Error Bars (Advanced)
    {
        id: 'teff_err1',
        label: 'Temp Error (+)',
        description: 'Uncertainty in temperature upper bound',
        min: 0,
        max: 1000,
        required: true,
        category: 'advanced',
    },
    {
        id: 'teff_err2',
        label: 'Temp Error (-)',
        description: 'Uncertainty in temperature lower bound',
        min: -1000,
        max: 0,
        required: true,
        category: 'advanced',
    },
    {
        id: 'logg_err1',
        label: 'Gravity Error (+)',
        description: 'Uncertainty in surface gravity upper bound',
        min: 0,
        max: 1,
        required: true,
        category: 'advanced',
    },
    {
        id: 'logg_err2',
        label: 'Gravity Error (-)',
        description: 'Uncertainty in surface gravity lower bound',
        min: -1,
        max: 0,
        required: true,
        category: 'advanced',
    },
    {
        id: 'feh_err1',
        label: 'Metallicity Error (+)',
        description: 'Uncertainty in metallicity upper bound',
        min: 0,
        max: 1,
        required: true,
        category: 'advanced',
    },
    {
        id: 'feh_err2',
        label: 'Metallicity Error (-)',
        description: 'Uncertainty in metallicity lower bound',
        min: -1,
        max: 0,
        required: true,
        category: 'advanced',
    },
    {
        id: 'mass_err1',
        label: 'Mass Error (+)',
        description: 'Uncertainty in mass upper bound',
        min: 0,
        max: 1,
        required: true,
        category: 'advanced',
    },
    {
        id: 'mass_err2',
        label: 'Mass Error (-)',
        description: 'Uncertainty in mass lower bound',
        min: -1,
        max: 0,
        required: true,
        category: 'advanced',
    },
    {
        id: 'radius_err1',
        label: 'Radius Error (+)',
        description: 'Uncertainty in radius upper bound',
        min: 0,
        max: 1,
        required: true,
        category: 'advanced',
    },
    {
        id: 'radius_err2',
        label: 'Radius Error (-)',
        description: 'Uncertainty in radius lower bound',
        min: -1,
        max: 0,
        required: true,
        category: 'advanced',
    },
];
