import { FeatureConfig } from '@/types/prediction';

export const featureConfig: FeatureConfig[] = [
    // ── Planet Features ───────────────────────────────────────
    {
        id: 'koi_period',
        label: 'Orbital Period',
        description: 'Time taken for the planet to orbit its star (days)',
        min: 0,
        max: 1000,
        required: true,
        category: 'core',
        section: 'planet',
    },
    {
        id: 'koi_duration',
        label: 'Transit Duration',
        description: 'Duration of the planetary transit (hours)',
        min: 0,
        max: 100,
        required: true,
        category: 'core',
        section: 'planet',
    },
    {
        id: 'koi_depth',
        label: 'Transit Depth',
        description: 'Fraction of stellar flux lost during transit (ppm)',
        min: 0,
        max: 1000000,
        required: true,
        category: 'core',
        section: 'planet',
    },
    {
        id: 'koi_impact',
        label: 'Impact Parameter',
        description: 'Sky-projected distance between disk centers',
        min: 0,
        max: 5,
        required: true,
        category: 'core',
        section: 'planet',
    },
    {
        id: 'koi_model_snr',
        label: 'Model SNR',
        description: 'Transit depth normalized by noise',
        min: 0,
        max: 10000,
        required: true,
        category: 'core',
        section: 'planet',
    },
    {
        id: 'koi_num_transits',
        label: 'Number of Transits',
        description: 'Number of transit events observed',
        min: 0,
        max: 1000,
        required: true,
        category: 'core',
        section: 'planet',
    },

    // ── Stellar Features ──────────────────────────────────────
    {
        id: 'st_teff',
        label: 'Stellar Temperature',
        description: 'Effective temperature of the star (Kelvin)',
        min: 0,
        max: 10000,
        required: true,
        category: 'core',
        section: 'stellar',
    },
    {
        id: 'st_logg',
        label: 'Stellar Surface Gravity',
        description: 'Base-10 logarithm of surface gravity (cm/s²)',
        min: 0,
        max: 6,
        required: true,
        category: 'core',
        section: 'stellar',
    },
    {
        id: 'st_met',
        label: 'Stellar Metallicity',
        description: 'Logarithm of iron-to-hydrogen ratio',
        min: -2,
        max: 1,
        required: true,
        category: 'core',
        section: 'stellar',
    },
    {
        id: 'st_mass',
        label: 'Stellar Mass',
        description: 'Mass of the star in solar masses',
        min: 0,
        max: 20,
        required: true,
        category: 'core',
        section: 'stellar',
    },
    {
        id: 'st_radius',
        label: 'Stellar Radius',
        description: 'Radius of the star in solar radii',
        min: 0,
        max: 200,
        required: true,
        category: 'core',
        section: 'stellar',
    },
];
